### ISSUE TITLE
css fix enabled  .title

### ISSUE THREAD

**Issue by djmisterjon** [pixijs/pixi-filters#165]
https://github.com/pixijs/pixi-filters/blob/3138e6d973251d1d46d53c443369636fb36b79fb/tools/demo/index.css#L37

should green , I am not color-blind, but white contrast on white.
difficult to see first-hand.
thanks

```css
.dg.enabled .title {
    color: #00ff2d;
}
```
